[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v --tb=short -W ignore::sqlalchemy.exc.LegacyAPIWarning -W ignore::DeprecationWarning
filterwarnings =
    ignore::sqlalchemy.exc.LegacyAPIWarning
    ignore::DeprecationWarning
